test_average (__main__.TestExercice) ... ok
test_square (__main__.TestExercice) ... ok
test_square_root (__main__.TestExercice) ... ok
test_to_celsius (__main__.TestExercice) ... FAIL
test_to_degrees (__main__.TestExercice) ... FAIL
test_to_farenheit (__main__.TestExercice) ... FAIL
test_to_radians (__main__.TestExercice) ... FAIL

======================================================================
FAIL: test_to_celsius (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 98, in test_to_celsius
    'Mauvais calcul de farenheit -> celsius'
AssertionError: Lists differ: [-17.8, -31.7, 232.8] != [-17.77777777777778, -31.666666666666664, 232.77777777777777]

First differing element 0:
-17.8
-17.77777777777778

- [-17.8, -31.7, 232.8]
+ [-17.77777777777778, -31.666666666666664, 232.77777777777777] : Mauvais calcul de farenheit -> celsius

======================================================================
FAIL: test_to_degrees (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 86, in test_to_degrees
    'Mauvais calcul de radians -> degres'
AssertionError: Lists differ: [(114.59155902616465, 35.493541569878744, 2[195 chars]128)] != [(79.0980174562859, 5.881047377154118, 29.6[197 chars]998)]

First differing element 0:
(114.59155902616465, 35.493541569878744, 2129.6124941927246)
(79.0980174562859, 5.881047377154118, 29.612494192724625)

- [(114.59155902616465, 35.493541569878744, 2129.6124941927246),
-  (-229.1831180523293, 49.01291686024251, 2940.7750116145507),
-  (286.4788975654116, 28.73385392469686, 1724.0312354818116),
-  (234.3397382085067, 20.384292510402133, 1223.057550624128)]
+ [(79.0980174562859, 5.881047377154118, 29.612494192724625),
+  (-278.1960349125718, 48.23790524569176, 0.7750116145507491),
+  (257.74504364071475, -15.297381557114704, 44.031235481811564),
+  (213.95544569810457, -2.673258113725865, 23.057550624127998)] : Mauvais calcul de radians -> degres

======================================================================
FAIL: test_to_farenheit (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 110, in test_to_farenheit
    'Mauvais calcul de celsius -> farenheit'
AssertionError: Lists differ: [32.0, -13.0, 843.8] != [32.0, -13.0, 843.8000000000001]

First differing element 2:
843.8
843.8000000000001

- [32.0, -13.0, 843.8]
+ [32.0, -13.0, 843.8000000000001]
?                    ++++++++++++
 : Mauvais calcul de celsius -> farenheit

======================================================================
FAIL: test_to_radians (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 67, in test_to_radians
    'Mauvais calcul de degres -> radians'
AssertionError: Lists differ: [-0.0[13 chars]503, 0.17598251810595045, 6.283490739798685, 6.997344948274799] != [-0.0[13 chars]503, 0.17598251810595048, 6.283490739798685, 6.9973449482748]

First differing element 1:
0.17598251810595045
0.17598251810595048

+ [-0.08668468618238503, 0.17598251810595048, 6.283490739798685, 6.9973449482748]
- [-0.08668468618238503,
-  0.17598251810595045,
-  6.283490739798685,
-  6.997344948274799] : Mauvais calcul de degres -> radians

----------------------------------------------------------------------
Ran 7 tests in 0.006s

FAILED (failures=4)
